add dotnet 6 target
matteofabbri/AspNetCore.Identity.Mongo pull request #117
Opened 2021-12-21 23:26 UTC by sgentry

What does this implement/fix? Explain your changes.
---------------------------------------------------
Adds support for targeting net6.0 and updates dependencies

Does this close any currently open issues?
------------------------------------------
No

Any relevant logs, error output, etc?
-------------------------------------
No

Where has this been tested?
---------------------------
**Operating System:** Windows 11

**.Net Core Verion:** net6.0

Does this introduce a breaking change?
-----------------------------------------

- [ ] Yes
- [x] No

Any other comments?
-------------------
Not 100% sure about updating `Microsoft.Extensions.Identity.Core` & `Microsoft.Extensions.Identity.Stores` from v2->v6 but prefer to use latest if not a breaking change. I've tested creating new user and login/logoff with sample application I'm working on. I can downgrade those if there's concerns.

2022-03-14 08:47 UTC, theranger commented
Could we get this into mainline? Many projects cannot be migrated to .net6 because this package is not compatible with that version.

2022-03-17 11:56 UTC, jaytonic commented
@matteofabbri Any chance you could accept this PR? I also need it for a project that runs on .Net 6

2022-03-18 09:21 UTC, Lukejkw commented
We're using this package with .NET 6 without issue @theranger

2022-03-24 19:41 UTC, daviddesmet requested changes

2022-03-24 19:41 UTC, daviddesmet commented on src/AspNetCore.Identity.Mongo/AspNetCore.Identity.Mongo.csproj
>  	</ItemGroup>
This block is specific for .NET Standard 2.1, it shouldn't reference other versions that are not part of it.

2022-03-24 19:43 UTC, daviddesmet commented on src/AspNetCore.Identity.Mongo/AspNetCore.Identity.Mongo.csproj
>  	</ItemGroup>
In other words, that block shouldn't have changed.

2024-02-07 20:52 UTC, merged